name: Publish Library to Repository
on:
  push:
    branches:
      - lucifer-dev

jobs:
  publish-jar:
    runs-on: ubuntu-latest

    steps:
      - name: "GIT: Checkout Action Version"
        uses: actions/checkout@v3

      - name: "JAVA: Set Up JAVA Version 8"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: "GRADLE: Publish Library"
        run: ./gradlew test clean publish
        env:
          GH_PKG_USERNAME: ${{ vars.PUB_JAR_USERNAME }}
          GH_PKG_TOKEN: ${{ secrets.PUB_JAR_TOKEN }}